server:
  port: 8080

logging:
  level:
    root: info
    ch.sbb: info
  pattern:
    console: '[%d] [%t] %-5p %c - corid=%X{X-B3-TraceId:-} %m%n'

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  flyway:
    locations: classpath:/db/migration/common,/db/migration/dev #,/db/migration/${CLOUDPROFILES_ACTIVE}
    baseline-version: 0
#    user: ${FLYWAY_USERNAME}
#    password: ${FLYWAY_PASSWORD}
#    schemas: ${DATASOURCE_SCHEMA}


