/*
 * Copyright (C) Schweizerische Bundesbahnen SBB, 2019.
 */

package ch.sbb.kat;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring boot config for the application.
 *
 * @author ue64007 (Manuel Wallrapp), generated by ESTA Initializr
 * @since 1.0.0, 2017.
 */
@SpringBootApplication
public class DemoFlywayApp {
    public static void main(String[] args) {
        SpringApplication.run(DemoFlywayApp.class, args);
    }
}
